### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by joshuacox** [sameersbn/docker-redmine#107]
When initializing the 2.6-latest branch with a new container I am getting:
```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.
```
the internal logs look like this:
```
==> /var/log/redmine/redmine/production.log <==
Started GET "/" for 127.0.0.1 at 2015-05-21 14:44:02 +0000
Processing by WelcomeController#index as HTML
DEPRECATION WARNING: You're trying to create an attribute `mail'. Writing arbitrary attributes on a model is deprecated. Please just use `attr_writer` etc. (called from mail= at /home/redmine/redmine/app/models/user.rb:151)
Completed 500 Internal Server Error in 39.0ms

NoMethodError (undefined method `mail_changed?' for #<AnonymousUser:0x00000004132938>):
  app/models/user.rb:101:in `block in <class:User>'
  app/models/user.rb:654:in `anonymous'
  app/models/user.rb:646:in `current'
  app/controllers/application_controller.rb:103:in `user_setup'



==> /var/log/redmine/nginx/redmine_access.log <==
172.17.42.1 - - [21/May/2015:14:44:02 +0000] "GET / HTTP/1.1" 500 648 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.7.0"
```
I followed the 'quickstart' nearly identically except I changed to 2.6-latest instead of 3:

`sameersbn/redmine:2.6-latest`

**Comment by sameersbn** [comment]
@joshuacox can you share a sample docker command or `docker-compose.yml` file. It looks like some variable could have been misconfigured or maybe some variable needs escaping.

**Comment by joshuacox** [comment]
sure here's the exact commands, first postgres:
```
        docker run --name=postgresql-redmine -d \
        --env='DB_NAME=redmine_production' \
        --cidfile="postgrescid" \
        --env='DB_USER=redmine' --env='DB_PASS=password' \
        --volume=/tmp:/tmp \
        --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql \
        sameersbn/postgresql:9.4
```
then redmine itself:
```
        docker run --name=redminit \
        -d \
        --link=postgresql-redmine:postgresql --publish=10083:80 \
        --env='REDMINE_PORT=10083' \
        --volume=/srv/docker/redmine/redmine:/home/redmine/data \
        --volume=/tmp:/tmp \
        --cidfile="cid" \
        sameersbn/redmine:2.6-latest
```

**Comment by joshuacox** [comment]
`sudo rm -Rf /srv/docker`   <-- did the trick, I had something carrying over from the 3.x install I think @sameersbn  thanks for the quick response, I think all is good.
