### ISSUE TITLE
Unable to open Atom feed

### ISSUE THREAD

**Issue by JosBode** [sameersbn/docker-redmine#198]
Hello, I get an **Internal error** when opening any Atom feed. What could be causing this?

Secret token is generated, user keys are generated and matching. PDF/CSV works fine...

Docker Redmine version: 3.2.1-6

Error taken from production.log:
```
Started GET "/issues/574.atom?key=b292fe7784774e2b43f869a048f356625c10c93f" for 127.0.0.1 at 2016-05-25 08:59:28 +0000
Processing by IssuesController#show as ATOM
  Parameters: {"key"=>"b292fe7784774e2b43f869a048f356625c10c93f", "id"=>"574"}
  Current user: admin (id=1)
  Rendered journals/index.builder (4.3ms)
Completed 500 Internal Server Error in 29ms (ActiveRecord: 4.1ms)

ActionView::Template::Error (No route matches {:action=>"index", :controller=>"welcome", :format=>"atom", :id=>"574"}):
    4:   xml.link    "rel" => "self", "href" => url_for(:format => "atom", :key=> User.current.rss_key, :only_path => false)
    5:   xml.link    "rel" => "alternate", "href" => home_url
    6:   xml.id      home_url
    7:   xml.icon    favicon_url
    8:   xml.updated((@journals.first ? @journals.first.event_datetime : Time.now).xmlschema)
    9:   xml.author  { xml.name "#{Setting.app_title}" }
   10:   @journals.each do |change|
  app/helpers/application_helper.rb:1291:in "favicon_url"
  app/views/journals/index.builder:7:in "block in "_app_views_journals_index_builder___3842294612854714864_72320080"
  app/views/journals/index.builder:2:in "_app_views_journals_index_builder___3842294612854714864_72320080"
  app/controllers/issues_controller.rb:121:in "block (2 levels) in show"
  app/controllers/issues_controller.rb:115:in "show"
  lib/redmine/sudo_mode.rb:63:in "sudo_mode"
```

**Comment by gnovelli** [comment]
Closed. And the solution?

**Comment by guillaume-uH57J9** [comment]
Getting the same problem with thin 1.6.3, and redmine 3.3.1. 
Hi @JosBode would you mind adding a comment on how you finally solved this, if you remember it. 
That's be appreciated.
