### ISSUE TITLE
Get 500 err while create new issue

### ISSUE THREAD

**Issue by zdnet** [sameersbn/docker-redmine#235]
Could you please help to check?
Email notification is disabled in setting.

paste log:

Started POST "/projects/ca-ios/issues" for 127.0.0.1 at 2016-11-22 01:02:44 +0000
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"k6WH68HOs30CDwnne3vBsqnTR+M7TGpJmLVnzKhw3B+LvckwEM0MM8tvnomge5XGJ98DgOkslmmWkupbeY6SIQ==", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "tracker_id"=>"5", "subject"=>"test4", "description"=>"test4", "status_id"=>"3", "priority_id"=>"3", "assigned_to_id"=>"6", "category_id"=>"1", "fixed_version_id"=>"1", "parent_issue_id"=>"", "start_date"=>"2016-11-22", "due_date"=>"", "estimated_hours"=>"2", "done_ratio"=>"0", "watcher_user_ids"=>["6"]}, "was_default_status"=>"3", "commit"=>"new", "project_id"=>"ca-ios"}
  Current user: admin (id=1)
  Rendered mailer/_issue.text.erb (5.4ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (7.5ms)
  Rendered mailer/_issue.html.erb (3.4ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (5.1ms)
**Completed 500 Internal Server Error in 2289ms (ActiveRecord: 13.1ms)**

NoMethodError (undefined method `split' for nil:NilClass):
  plugins/redmine_slack/lib/redmine_slack/listener.rb:214:in `channels_for_project'
  plugins/redmine_slack/lib/redmine_slack/listener.rb:208:in `channels_for_project'
  plugins/redmine_slack/lib/redmine_slack/listener.rb:7:in `controller_issues_new_after_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:141:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by zdnet** [comment]
seems it is caused by plugin redmine_slack ... let me uninstall it..
