### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by dropped** [sameersbn/docker-redmine#244]
Hi guys.

I'm trying running redmine with HTTPS support but getting some errors.  

```
docker run -d --publish 7000:80 --publish 7443:443 \
  -e DB_ADAPTER='postgresql' \
  -e DB_HOST='xxx' \
  -e DB_NAME='xxx' \
  -e DB_PASS='xxx' \
  -e DB_TYPE='postgres' \
  -e DB_USER='xxx' \
  -e REDMINE_SECRET_TOKEN='xxx' \
  -e REDMINE_HTTPS='true' \
  -e REDMINE_PORT='7443' \
  -e SMTP_ENABLED='true' \
  -e SMTP_HOST='xxx' \
  -e SMTP_METHOD='smtp' \
  -e SMTP_PORT='xxx' \
  -e SMTP_STARTTLS='false' \
  --volume=/bla/redmine/redmine/:/home/redmine/data \
  sameersbn/redmine:3.2.0
```

As we can see the logs:

```
docker logs silly_franklin
Waiting for database server to accept connections
Installing plugins...
Installing themes...
2016-12-21 13:26:34,346 CRIT Supervisor running as root (no user in config file)
2016-12-21 13:26:34,346 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2016-12-21 13:26:34,346 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
2016-12-21 13:26:34,346 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2016-12-21 13:26:34,372 INFO RPC interface 'supervisor' initialized
2016-12-21 13:26:34,372 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-12-21 13:26:34,372 INFO supervisord started with pid 1
2016-12-21 13:26:35,374 INFO spawned: 'unicorn' with pid 132
2016-12-21 13:26:35,375 INFO spawned: 'cron' with pid 133
2016-12-21 13:26:35,376 INFO spawned: 'nginx' with pid 134
2016-12-21 13:26:36,477 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:36,477 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:36,477 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:40,847 INFO exited: unicorn (exit status 1; not expected)
2016-12-21 13:26:41,850 INFO spawned: 'unicorn' with pid 138
2016-12-21 13:26:42,851 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:43,085 INFO exited: unicorn (exit status 1; not expected)
2016-12-21 13:26:44,087 INFO spawned: 'unicorn' with pid 141
2016-12-21 13:26:45,089 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:45,128 INFO exited: unicorn (exit status 1; not expected)
2016-12-21 13:26:46,130 INFO spawned: 'unicorn' with pid 144
2016-12-21 13:26:47,131 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:47,168 INFO exited: unicorn (exit status 1; not expected)
2016-12-21 13:26:48,170 INFO spawned: 'unicorn' with pid 147
2016-12-21 13:26:49,172 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:49,214 INFO exited: unicorn (exit status 1; not expected)
2016-12-21 13:26:50,216 INFO spawned: 'unicorn' with pid 150
2016-12-21 13:26:51,217 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-21 13:26:51,245 INFO exited: unicorn (exit status 1; not expected)
``` 
Looking at unicorn logs:

```
tail -f /var/log/redmine/redmine/unicorn.stderr.log
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `eval'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `block in builder'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `call'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `call'
        from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `build_app!'
        from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:129:in `start'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
I, [2016-12-21T13:36:55.094743 #1048]  INFO -- : Refreshing Gem list
/home/redmine/redmine/config/environment.rb:2:in `require': /home/redmine/redmine/config/application.rb:75: syntax error, unexpected ',' (SyntaxError)
    config.session_store :cookie_store,, :secure => true
                                        ^
/home/redmine/redmine/config/application.rb:76: syntax error, unexpected =>, expecting keyword_end
      :key => '_redmine_session',
             ^
/home/redmine/redmine/config/application.rb:76: syntax error, unexpected ',', expecting keyword_end
        from /home/redmine/redmine/config/environment.rb:2:in `<top (required)>'
        from config.ru:4:in `require'
        from config.ru:4:in `block in <main>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `eval'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `block in builder'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `call'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `call'
        from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `build_app!'
        from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:129:in `start'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
        from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
I, [2016-12-21T13:36:57.132136 #1052]  INFO -- : Refreshing Gem list
/home/redmine/redmine/config/environment.rb:2:in `require': /home/redmine/redmine/config/application.rb:75: syntax error, unexpected ',' (SyntaxError)
    config.session_store :cookie_store,, :secure => true
                                        ^
/home/redmine/redmine/config/application.rb:76: syntax error, unexpected =>, expecting keyword_end
      :key => '_redmine_session',
             ^
/home/redmine/redmine/config/application.rb:76: syntax error, unexpected ',', expecting keyword_end
```

I've realized if I don't use `-e REDMINE_HTTPS='true' ` it works but without HTTPS support, of course.

Am I missing something? Is there another env var to set?

Thanks.

**Comment by dropped** [comment]
I've just seem #160. Now I'm using sameersbn/redmine:3.2.0-2 image and it's working.

Please, close this.

Thanks.
