### ISSUE TITLE
Internal error happened on /my/account and /setting page 

### ISSUE THREAD

**Issue by normansu-tw** [sameersbn/docker-redmine#337]
Here is my error message in log file.

> Started GET "/my/account" for 127.0.0.1 at 2018-05-11 09:16:20 +0000
> Processing by MyController#account as HTML
>   Current user: admin (id=1)
>   Rendered my/account.html.erb within layouts/base (551.0ms)
> Completed 500 Internal Server Error in 563ms (ActiveRecord: 2.5ms)
> 
> ActionView::Template::Error (can not load translations from /home/redmine/redmine/plugins/redmine_issues_tree/config/locales/pt-BR.yml: #<Psych::SyntaxError: (/home/redmine/redmine/plugins/redmine_issues_tree/config/locales/pt-BR.yml): did not find expected key while parsing a block mapping at line 10 column 7>):
>     22:   <p><%= f.text_field :lastname, :required => true %></p>
>     23:   <p><%= f.text_field :mail, :required => true %></p>
>     24:   <% unless @user.force_default_language? %>
>     25:   <p><%= f.select :language, lang_options_for_select %></p>
>     26:   <% end %>
>     27:   <% if Setting.openid? %>
>     28:   <p><%= f.text_field :identity_url  %></p>
>   lib/redmine/i18n.rb:185:in `init_translations'
>   lib/redmine/i18n.rb:199:in `lookup'
>   lib/redmine/i18n.rb:121:in `block in languages_options'
>   lib/redmine/i18n.rb:121:in `select'
>   lib/redmine/i18n.rb:121:in `languages_options'
>   lib/redmine/i18n.rb:126:in `block in languages_options'
>   lib/redmine/i18n.rb:125:in `languages_options'
>   app/helpers/application_helper.rb:1180:in `lang_options_for_select'
>   app/views/my/account.html.erb:25:in `block in _app_views_my_account_html_erb___51763069495662415_85841600'
>   app/helpers/application_helper.rb:1190:in `labelled_form_for'
>   app/views/my/account.html.erb:14:in `_app_views_my_account_html_erb___51763069495662415_85841600'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
>

**Comment by normansu-tw** [comment]
Sorry , I have found this bug caused by redmine_issues_tree plugin.
