### ISSUE TITLE
web page:   Internal error

### ISSUE THREAD

**Issue by JiangHeng12138** [sameersbn/docker-redmine#351]
Hi,

I used docker-composed-mysql.yml script. Everything is started on container. I checked with ps command.

But I can't access the running redmine thong port 10083. web page  tells me: 

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.

I login with docker exec and cat log/product.log:

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine_production.settings' doesn't exist: SHOW FULL FIELDS FROM `settings`):
  app/models/setting.rb:231:in `check_cache'
  app/controllers/application_controller.rb:90:in `user_setup'

Seems mysql connect error. Any idea?

**Comment by jcormier** [comment]
Can you attach the `docker-compose up` output?

**Comment by jcormier** [comment]
```
 $ docker-compose -f docker-compose-mysql.yml up
Creating network "docker-redmine_default" with the default driver
Creating docker-redmine_mysql_1 ... done
Creating docker-redmine_redmine_1 ... done
Attaching to docker-redmine_mysql_1, docker-redmine_redmine_1
mysql_1    | Installing database...
redmine_1  | Initializing logdir...
redmine_1  | Initializing datadir...
redmine_1  | Symlinking dotfiles...
redmine_1  | Installing configuration templates...
redmine_1  | Configuring redmine...
mysql_1    | Starting MySQL server...
mysql_1    | Waiting for database server to accept connections.
mysql_1    | Creating debian-sys-maint user...
mysql_1    | Creating database "redmine_production"...
mysql_1    | Granting access to database "redmine_production" for user "redmine"...
mysql_1    | 2018-08-03T13:29:49.496406Z mysqld_safe Logging to syslog.
mysql_1    | 2018-08-03T13:29:49.519704Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
redmine_1  | Configuring redmine::database.........
redmine_1  | Configuring redmine::unicorn...
redmine_1  | Configuring redmine::secret_token...
redmine_1  | Generating a session token...
redmine_1  | Note:
redmine_1  |   All old sessions will become invalid.
redmine_1  |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1  |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1  | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1  | Configuring redmine::sudo_mode...
redmine_1  | Configuring redmine::autologin_cookie...
redmine_1  | Configuring redmine::backups...
redmine_1  | Configuring nginx...
redmine_1  | Configuring nginx::redmine...
redmine_1  | Installing plugins...
redmine_1  | Installing themes...
redmine_1  | 2018-08-03 18:59:50,878 CRIT Supervisor running as root (no user in config file)
redmine_1  | 2018-08-03 18:59:50,878 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
redmine_1  | 2018-08-03 18:59:50,878 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
redmine_1  | 2018-08-03 18:59:50,878 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
redmine_1  | 2018-08-03 18:59:50,896 INFO RPC interface 'supervisor' initialized
redmine_1  | 2018-08-03 18:59:50,896 CRIT Server 'unix_http_server' running without any HTTP authentication checking
redmine_1  | 2018-08-03 18:59:50,896 INFO supervisord started with pid 1
redmine_1  | 2018-08-03 18:59:51,899 INFO spawned: 'unicorn' with pid 247
redmine_1  | 2018-08-03 18:59:51,901 INFO spawned: 'cron' with pid 248
redmine_1  | 2018-08-03 18:59:51,903 INFO spawned: 'nginx' with pid 249
redmine_1  | 2018-08-03 18:59:53,341 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2018-08-03 18:59:53,341 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2018-08-03 18:59:53,341 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker-redmine_redmine_1 ... done
Stopping docker-redmine_mysql_1   ... done
 09:30:36  jcormier  ~  dockers  docker-redmine   master §                                                                                                                                       4d 0h 11m 
 $ docker-compose -f docker-compose-mysql.yml down
Removing docker-redmine_redmine_1 ... done
Removing docker-redmine_mysql_1   ... done
Removing network docker-redmine_default
```

**Comment by JiangHeng12138** [comment]
This question is on my company's computer and I will reply to you on Monday. 
thank you！

**Comment by JiangHeng12138** [comment]
here is output:

ts@ts-OptiPlex-3020:~/Docker/docker-redmine$ docker-compose -f docker-compose-mysql.yml up
Pulling mysql (sameersbn/mysql:latest)...
latest: Pulling from sameersbn/mysql
6b98dfc16071: Already exists
4001a1209541: Already exists
6319fc68c576: Already exists
b24603670dc3: Already exists
97f170c87c6f: Already exists
f2904dd10b35: Pull complete
a9d78b5b8be5: Pull complete
Digest: sha256:7e12df4332c74aed0d28871d13be0da3cbaa072d1219635645d55470bfe28faf
Status: Downloaded newer image for sameersbn/mysql:latest
Pulling redmine (sameersbn/redmine:3.4.6)...
3.4.6: Pulling from sameersbn/redmine
cb56c90f0b30: Already exists
0acc551e5716: Already exists
8956dcd35143: Already exists
908242721214: Already exists
b44ff14dd3bb: Already exists
707fcc5f355b: Already exists
731fc417ced9: Already exists
dd703ad06df3: Already exists
30c23778cf21: Already exists
ad7acb28644a: Already exists
4db700937b9f: Already exists
b683858c9e22: Already exists
Digest: sha256:48c263882e2704fdf6d0e7cf89fb505526480ae622fe3981f4a656714807dd9e
Status: Downloaded newer image for sameersbn/redmine:3.4.6
Recreating dockerredmine_mysql_1
Recreating dockerredmine_redmine_1
Attaching to dockerredmine_mysql_1, dockerredmine_redmine_1
mysql_1    | Creating database "redmine_production"...
redmine_1  | Initializing logdir...
mysql_1    | Granting access to database "redmine_production" for user "redmine"...
redmine_1  | Initializing datadir...
mysql_1    | 2018-08-06T01:27:50.094513Z mysqld_safe Logging to syslog.
mysql_1    | 2018-08-06T01:27:50.111023Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
redmine_1  | Symlinking dotfiles...
redmine_1  | Installing configuration templates...
redmine_1  | Configuring redmine...
redmine_1  | Configuring redmine::database
redmine_1  | Configuring redmine::unicorn...
redmine_1  | Configuring redmine::secret_token...
redmine_1  | Generating a session token...
redmine_1  | Note:
redmine_1  |   All old sessions will become invalid.
redmine_1  |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1  |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1  | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1  | Configuring redmine::sudo_mode...
redmine_1  | Configuring redmine::autologin_cookie...
redmine_1  | Configuring redmine::backups...
redmine_1  | Configuring nginx...
redmine_1  | Configuring nginx::redmine...
redmine_1  | Installing plugins...
redmine_1  | Installing themes...
redmine_1  | 2018-08-06 06:58:05,229 CRIT Supervisor running as root (no user in config file)
redmine_1  | 2018-08-06 06:58:05,229 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
redmine_1  | 2018-08-06 06:58:05,229 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
redmine_1  | 2018-08-06 06:58:05,229 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
redmine_1  | 2018-08-06 06:58:05,464 INFO RPC interface 'supervisor' initialized
redmine_1  | 2018-08-06 06:58:05,464 CRIT Server 'unix_http_server' running without any HTTP authentication checking
redmine_1  | 2018-08-06 06:58:05,465 INFO supervisord started with pid 1
redmine_1  | 2018-08-06 06:58:06,466 INFO spawned: 'unicorn' with pid 218
redmine_1  | 2018-08-06 06:58:06,467 INFO spawned: 'cron' with pid 219
redmine_1  | 2018-08-06 06:58:06,468 INFO spawned: 'nginx' with pid 220
redmine_1  | 2018-08-06 06:58:07,469 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2018-08-06 06:58:07,469 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2018-08-06 06:58:07,469 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)



May be a problem with mysql?

**Comment by jcormier** [comment]
My guess would be that the database wasn't properly setup. 

I deleted my mysql directory and got the same error message as you. 

```sudo rm -rf /srv/docker/redmine/mysql/```

The start script looks for a VERSION file and won't migrate the database if it exists and the version hasn't changed.

https://github.com/sameersbn/docker-redmine/blob/e4ced28701601b7e9d7fdb11d9a62d54283f337d/assets/runtime/functions#L889

To reset the state, I ran the following, which brought me back to a working system.
```
docker-compose -f docker-compose-mysql.yml down
sudo rm -rf /srv/docker/redmine/redmine/tmp
sudo rm -rf /srv/docker/redmine/mysql/
```

**Comment by JiangHeng12138** [comment]
the problem is solved,thank you for your reply.
