### ISSUE TITLE
mysql gem error after restart

### ISSUE THREAD

**Issue by simonbuehler** [sameersbn/docker-redmine#356]
hi,

i tried to add memcache but then those errors started:

```
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2.rb:31:in `require': libmysqlclient.so.18: cannot open shared object file: No such file or directory - /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2/mysql2.so (LoadError)
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2.rb:31:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `each'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `block in require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `each'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.3/lib/bundler.rb:114:in `require'
        from /home/redmine/redmine/config/application.rb:5:in `<top (required)>'
        from /home/redmine/redmine/config/environment.rb:2:in `require'
        from /home/redmine/redmine/config/environment.rb:2:in `<top (required)>'
        from config.ru:4:in `require'
        from config.ru:4:in `block in <main>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn.rb:56:in `eval'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn.rb:56:in `block in builder'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/data/tmp/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:795:in `build_app!'
        from /home/redmine/data/tmp/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:139:in `start'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `load'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `<main>'
I, [2018-09-03T08:39:10.216528 #1173]  INFO -- : Refreshing Gem list
```

what is the reaseon for this and how to fix it?

**Comment by simonbuehler** [comment]
restored image, worksnow
