### ISSUE TITLE
unicorn exit status 1 with mysql2 error.

### ISSUE THREAD

**Issue by whitehander** [sameersbn/docker-redmine#366]
I got 502 Bad Gateway error with docker-compose

docker's log showing unicorn exit status 1 error.

below is /var/log/redmine/redmine/unicorn.stderr.log
```
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': libmysqlclient.so.18: cannot open shared object file: No such file or directory - /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2/mysql2.so (LoadError)
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2.rb:31:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `each'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `block in require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `each'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `require'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler.rb:114:in `require'
        from /home/redmine/redmine/config/application.rb:5:in `<top (required)>'
        from /home/redmine/redmine/config/environment.rb:2:in `require'
        from /home/redmine/redmine/config/environment.rb:2:in `<top (required)>'
        from config.ru:4:in `require'
        from config.ru:4:in `block in <main>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/builder.rb:55:in `instance_eval'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn.rb:56:in `eval'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn.rb:56:in `block in builder'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/data/tmp/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:795:in `build_app!'
        from /home/redmine/data/tmp/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:139:in `start'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `load'
        from /home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `<main>'
```
but mysql2.so is existed.

docker-compose is no problem before version upgrade from 3.2.x

**Comment by jcormier** [comment]
Ensure that you have run docker-compose down when changing to a new redmine version.

**Comment by jcormier** [comment]
Closing due to inactivity. Reopen if this is still an issue
