### ISSUE TITLE
uninitialized constant Rake::TestTask

### ISSUE THREAD

**Issue by nmihaica** [sameersbn/docker-redmine#414]
Tried clean setup, but setting up containers failed to work. Precisely, redmine container.

```
redmine_1     | Migrating plugins. Please be patient, this could take a while...
redmine_1     | rake aborted!
redmine_1     | NameError: uninitialized constant Rake::TestTask
redmine_1     | /home/redmine/redmine/plugins/redmine_issue_templates/lib/tasks/test.rake:7:in `block in <top (required)>'
redmine_1     | /home/redmine/redmine/plugins/redmine_issue_templates/lib/tasks/test.rake:1:in `<top (required)>'
redmine_1     | /home/redmine/redmine/lib/tasks/redmine.rake:202:in `block in <top (required)>'
redmine_1     | /home/redmine/redmine/lib/tasks/redmine.rake:202:in `each'
redmine_1     | /home/redmine/redmine/lib/tasks/redmine.rake:202:in `<top (required)>'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `each'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `run_tasks_blocks'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/application.rb:515:in `run_tasks_blocks'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:459:in `load_tasks'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/railtie.rb:190:in `public_send'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/railtie.rb:190:in `method_missing'
redmine_1     | /home/redmine/redmine/Rakefile:7:in `<top (required)>'
redmine_1     | /home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
redmine_1     | (See full trace by running task with --trace)
dockerredmine_redmine_1 exited with code 1

```

**Comment by jcormier** [comment]
I've never seen this error before.  What version of the image are you running?  How are you starting it?  What does clean setup mean to you?

**Comment by jcormier** [comment]
It looks like a plugin is causing the failure.  
```
plugins/redmine_issue_templates
```

This should be reported to the plugin maintainers.

**Comment by nmihaica** [comment]
@jcormier tried few images. It breaks on ubuntu 16.04, however on Debian Buster clean run works without errors.

**Comment by jcormier** [comment]
Hmm could you check on the status of SELinux?  It might be tripping you up. https://github.com/sameersbn/docker-redmine/issues/311#issuecomment-334913607

I haven't had any issues with ubuntu 16.04 or 18.04 as host fyi.
