### ISSUE TITLE
don't recognizance  attachment and bg-image in my dockerized redmine

### ISSUE THREAD

**Issue by karippery** [sameersbn/docker-redmine#416]
hello,
i have a problem after migrate redmine from host to docker container.
i copy folders like plugins, public and template from host machine to redmine docker container.
after restarting my redmine container themes and plugins  are working fine.
and i migrate all database to my docker container  that is also working fine 

problem is redmine don't recognizance the folder redmine/public/image folder  because of the i can't see my bg images and main issues is i can't see my wiki attachment and images.

why i can't see images inside my docker redmine.
Is there any folder i want to copy from host machine 

i attached redmine container logs
[error.txt](https://github.com/sameersbn/docker-redmine/files/4312588/error.txt)

```
The Gemfile's dependencies are satisfied
[2020-03-10 10:50:04] INFO  WEBrick 1.3.1
[2020-03-10 10:50:04] INFO  ruby 2.4.4 (2018-03-28) [x86_64-linux]
[2020-03-10 10:50:04] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.......
Using rake 12.3.1
Using i18n 0.7.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.8
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.9
Using crass 1.0.3
Using loofah 2.2.2
Using rails-html-sanitizer 1.0.4
Using actionview 4.2.8
Using rack 1.6.9
Using rack-test 0.6.3
Using actionpack 4.2.8
Using globalid 0.4.1
Using activejob 4.2.8
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.6
Using actionmailer 4.2.8
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.8
Using arel 6.0.4
Using activerecord 4.2.8
Using public_suffix 3.0.2
Using addressable 2.5.2
Using bundler 1.16.1
Using coderay 1.1.2
Using concurrent-ruby 1.0.5
Using css_parser 1.6.0
Fetching polyglot 0.3.5
Installing polyglot 0.3.5
Using thor 0.20.0
Using railties 4.2.8
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Using rails 4.2.8
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching deface 1.5.3
Installing deface 1.5.3
Fetching temple 0.8.2
Installing temple 0.8.2
Fetching tilt 2.0.10
Installing tilt 2.0.10
Fetching haml 5.1.2
Installing haml 5.1.2
Fetching sexp_processor 4.14.1
Installing sexp_processor 4.14.1
Fetching ruby_parser 3.14.2
Installing ruby_parser 3.14.2
Fetching html2haml 2.2.0
Installing html2haml 2.2.0
Fetching haml-rails 1.0.0
Installing haml-rails 1.0.0
Using htmlentities 4.3.4
Fetching json 2.3.0
Installing json 2.3.0 with native extensions
Fetching mixlib-shellout 3.0.9
Installing mixlib-shellout 3.0.9
Fetching socksify 1.7.1
Installing socksify 1.7.1
Fetching unicode-display_width 1.6.1
Installing unicode-display_width 1.6.1
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching jenkins_api_client 1.5.3
Installing jenkins_api_client 1.5.3
Using jquery-rails 3.1.4
Using mimemagic 0.3.2
Using net-ldap 0.12.1
Using pg 0.18.4
Using protected_attributes 1.1.4
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using rbpdf-font 1.19.1
Using rbpdf 1.19.3
Using redcarpet 3.4.0
Using request_store 1.0.5
Using rmagick 2.16.0
Using roadie 3.2.2
Using roadie-rails 1.1.1
Fetching will_paginate 3.3.0
Installing will_paginate 3.3.0
Bundle complete! 36 Gemfile dependencies, 72 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `/usr/local/bundle`
[2020-03-10 11:35:29] INFO  WEBrick 1.3.1
[2020-03-10 11:35:29] INFO  ruby 2.4.4 (2018-03-28) [x86_64-linux]
[2020-03-10 11:35:29] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
=> Booting WEBrick
=> Rails 4.2.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
sh: 1: darcs: not found
sh: 1: cvs: not found
failed to open trace file: [Errno 2] No such file or directory: '/home/redmine/.bzr.log'
[2020-03-10 12:21:27] FATAL SignalException: SIGTERM
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:171:in `select'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:171:in `block in start'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:33:in `start'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:158:in `start'
	/usr/local/bundle/gems/rack-1.6.9/lib/rack/handler/webrick.rb:34:in `run'
	/usr/local/bundle/gems/rack-1.6.9/lib/rack/server.rb:287:in `start'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/server.rb:80:in `start'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	bin/rails:4:in `require'
	bin/rails:4:in `<main>'
[2020-03-10 12:21:27] INFO  going to shutdown ...
[2020-03-10 12:21:27] INFO  WEBrick::HTTPServer#start done.
Exiting
Resolving dependencies...
The Gemfile's dependencies are satisfied
[2020-03-10 12:21:41] INFO  WEBrick 1.3.1
[2020-03-10 12:21:41] INFO  ruby 2.4.4 (2018-03-28) [x86_64-linux]
[2020-03-10 12:21:41] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
=> Booting WEBrick
=> Rails 4.2.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
sh: 1: darcs: not found
sh: 1: cvs: not found
failed to open trace file: [Errno 2] No such file or directory: '/home/redmine/.bzr.log'
[2020-03-10 12:38:22] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:39:16] WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true
[2020-03-10 12:39:16] WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true
[2020-03-10 12:42:16] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:20] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:20] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:17 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:20] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:18 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:21] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:21] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:19 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:21] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:20 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:23] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:24] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:24] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:17 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 12:42:27] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 13:04:29] FATAL SignalException: SIGTERM
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:171:in `select'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:171:in `block in start'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:33:in `start'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:158:in `start'
	/usr/local/bundle/gems/rack-1.6.9/lib/rack/handler/webrick.rb:34:in `run'
	/usr/local/bundle/gems/rack-1.6.9/lib/rack/server.rb:287:in `start'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/server.rb:80:in `start'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	/usr/local/bundle/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	bin/rails:4:in `require'
	bin/rails:4:in `<main>'
[2020-03-10 13:04:29] INFO  going to shutdown ...
[2020-03-10 13:04:29] INFO  WEBrick::HTTPServer#start done.
Exiting
Resolving dependencies...
The Gemfile's dependencies are satisfied
[2020-03-10 13:04:42] INFO  WEBrick 1.3.1
[2020-03-10 13:04:42] INFO  ruby 2.4.4 (2018-03-28) [x86_64-linux]
[2020-03-10 13:04:42] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
[2020-03-10 13:05:05] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 13:05:08] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 13:05:08] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 13:05:08] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 13:05:34] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-10 13:05:35] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13 
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
root@debian:~# 
```

**Comment by jcormier** [comment]
It doesn't look like you use our docker container as we don't use debian or webrick.  So I don't think I can help you.
