### ISSUE TITLE
redmine_dmsf installation problems

### ISSUE THREAD

**Issue by mcondarelli** [sameersbn/docker-redmine#428]
I'm trying to install [redmine_dmsf](https://github.com/danmunn/redmine_dmsf.git) plugin, but I get several problems (probably due to my incompetence).

issuing a plain: 
```
cd .../data/plugins
git clone https://github.com/danmunn/redmine_dmsf.git
```
results in a fatal error:
```
...
Installing plugins...
Installing gems required by plugins...
Your application has set without to "development:test". This will override the global value you are currently setting

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: dalli (>= 0) and dalli (~> 2.7.0). Bundler cannot continue.

 #  from /home/redmine/redmine/Gemfile:105
 #  -------------------------------------------
 #  gem "unicorn", "~> 5.4", "!=5.5.0"
 >  gem "dalli", "~> 2.7.0"
 #  -------------------------------------------
```
this is trivially cured by:
```
sed -i '/dalli/ s/$/,  "~> 2.7.0"/' Gemfile
```
... but I don't understand why this is actually needed is this an upstream problem or a my config missing something?

This, however, uncovers an underlying problem:
```
Installing plugins...
Installing gems required by plugins...
Your application has set without to "development:test". This will override the global value you are currently setting
Migrating plugins. Please be patient, this could take a while...
== 20170422104901 MigrateDocuments: migrating =================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Permission denied @ dir_s_mkdir - /var/www/redmine
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:142:in `disk_file'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:28:in `block in up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `loop'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:69:in `find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/querying.rb:11:in `find_each'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:25:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:817:in `exec_migration'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1212:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:510:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:542:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:483:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:497:in `block in migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
Errno::EACCES: Permission denied @ dir_s_mkdir - /var/www/redmine
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:142:in `disk_file'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:28:in `block in up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `loop'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:69:in `find_each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/querying.rb:11:in `find_each'
/home/redmine/redmine/plugins/redmine_dmsf/db/migrate/20170422104901_migrate_documents.rb:25:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:817:in `exec_migration'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1212:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:510:in `up'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:542:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:483:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:497:in `block in migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:496:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```
This seems to be linked to `redmine_dmsf` specific installation instructions:
```
...
6. The access rights must be set for web server, example: chown -R www-data:www-data plugins/redmine_dmsf.
...
```
this is a problem because `docker-redmine` will reset ownership to `1000:1000`.
How can I overcome the problem?

**Comment by mcondarelli** [comment]
**Update:**
one additional problem comes from fact `/var/www` (and children) is owned by `root` instead of standard `www-data`.
I tried to change it manually, but this leads to further errors:
```
root@d84b45cde1f5:/home/redmine/redmine# source $REDMINE_ASSETS_DIR/runtime/functions 
root@d84b45cde1f5:/home/redmine/redmine# ls -la /var/www
total 12
drwxr-xr-x 3 root root 4096 Jul  3 00:27 .
drwxr-xr-x 1 root root 4096 Jul  3 00:27 ..
drwxr-xr-x 2 root root 4096 Jul  3 00:27 html
root@d84b45cde1f5:/home/redmine/redmine# chown -R www-data:www-data /var/www
root@d84b45cde1f5:/home/redmine/redmine# ls -la /var/www
total 24
drwxr-xr-x 1 www-data www-data 4096 Jul  3 00:27 .
drwxr-xr-x 1 root     root     4096 Jul  3 00:27 ..
drwxr-xr-x 1 www-data www-data 4096 Jul  3 00:27 html
root@d84b45cde1f5:/home/redmine/redmine# install_plugins
Installing plugins...
Installing gems required by plugins...
Your application has set without to "development:test". This will override the global value you are currently setting
Migrating plugins. Please be patient, this could take a while...
Rails Error: Unable to access log file. Please ensure that /home/redmine/redmine/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /home/redmine/redmine/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:585:in `validate_secret_key_base'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:432:in `secret_key_base'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:176:in `key_generator'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:205:in `message_verifier'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.4.2/lib/active_storage/engine.rb:81:in `block (2 levels) in <class:Engine>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```
... and I'm unsure if this is the right way to pursue the problem.
Please advise.

**Comment by jcormier** [comment]
> root@d84b45cde1f5:/home/redmine/redmine# chown -R www-data:www-data /var/www

Don't try to modify the permissions from within the docker.

You want to make sure the redmine user and group is mapped to a valid ID on your server.  And then that the directory and files are owned by that user.  It can be www-data but doesn't have to be.
https://github.com/sameersbn/docker-redmine#mapping-host-user-and-group

**Comment by mcondarelli** [comment]
Thanks for the fast answer.

If I understand this correctly the link you sent this will map the "redmine" user in the running container to the given UID.
This *might* work in the specific issue, bu it is different from what I'm supposed to do: Apparently redmine_dmsf plugin "would like" to be able to run as the "www-data" user (which has full access to `/var/www`), presumably because parts are running in some CGI-like script.
In the container I see several problems:

1. `data/plugins/redmine_dmsf` is forced to be owned by the same user as the rest of redmine (`redmine`); this might be fixable making `redmine` == `www-data`.
2. `/var/www/html` is owned by `root` and apparently also forced; this is where actual error occurs.
3. `/home/redmine/redmine/log` is a *dangling* symlink to `/var/log/redmine/redmine` (there is no `/var/log/redmine`)

I am unsure if these are problems with upstream redmine_dmsf plugin or some kind of "incompatibility". 

Thanks in Advance

**Comment by jcormier** [comment]
I don't see any mention of /var/www in the instructions you linked.  Nor any reference to it in the source code.  This directory isn't even used by redmine in the container.

Per this instruction ```chown -R www-data:www-data plugins/redmine_dmsf``` I assume they default to storing their files inside the plugins directory.  Which should have been copied to this location inside the docker /home/redmine/redmine/plugins.  However, this location isn't part of the persistent mounted volume and would get removed anytime the container is taken down.  You might be able to change their settings to put the storage location in /home/redmine/data which is persistent.
https://github.com/danmunn/redmine_dmsf/blob/master/init.rb

The plugin should run under the same user as the rest of redmine which would be the redmine user (UID/GID of whatever you map it to).  I don't believe there is any way a plugin could change its username, only root should be able to do that.

It seems like this plugin is pretty peculiar, and may take some tweaking to get it to work under the way we have redmine setup...


> /home/redmine/redmine/log is a dangling symlink to /var/log/redmine/redmine (there is no /var/log/redmine)
I mounted a volume to /var/log/redmine/redmine so the logs were persistent between restarts of the container.  Seems like this needs to be documented.

**Comment by mcondarelli** [comment]
It turns out problem was actually with `/var/www` being owned by `root`.
I was able to cure the problem with the following `data/plugins/pre-install.sh`:
```
#!/bin/sh -x
chown -Rc www-data:www-data /var/www
chmod ugo+w /var/www
```
I am unsure if this "wide open" setup is actually needed, but it works for me.
Thanks

**Comment by jcormier** [comment]
Alright glad you found a fix.  I would make sure that where ever it's storing its files, you have that mounted in a volume so you don't lose data.

**Comment by mcondarelli** [comment]
Apparently files are stored in `data/files/dmsf` (so they should be safe and backed up).
I was able to transport a whole old system (3.3.10) to latest(4.1.1) with full conversion from MySql (actually MariaDB) to SQLite3, using a backup as "source".
I will do some experimenting and report back (I also implemented backup/restore for SQLite, but I didn't test it yet).
One strange thing I found is there is a `dotfiles.tar.gz`, but that is *not* in gzip format (plain `tar`); did I mess something?

I will follow this on the SQLite thread.
Many thanks.

**Comment by jcormier** [comment]
Huh that's interesting, the backup uses ```tar -caf``` and is given the .tar.gz extension.  I would think the automatic "-a" argument would auto gzip the file.
https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L527

Just tested using 4.1.1-3 and they all look like they are properly gzipped.

```
 $ file *
1594325694_redmine_backup.tar: POSIX tar archive (GNU)
backup_information.yml:        ASCII text
database.sql.gz:               gzip compressed data, was "database.sql", last modified: Thu Jul  9 20:14:54 2020, from Unix
dotfiles.tar.gz:               gzip compressed data, last modified: Thu Jul  9 20:14:54 2020, from Unix
files.tar:                     POSIX tar archive (GNU)
plugins.tar.gz:                gzip compressed data, last modified: Thu Jul  9 20:14:54 2020, from Unix
themes.tar.gz:                 gzip compressed data, last modified: Thu Jul  9 20:14:54 2020, from Unix
```

>  I will do some experimenting and report back (I also implemented backup/restore for SQLite, but I didn't test it yet).

That's helpful, I think the sqlite backup feature was the only thing I was missing from the sqlite branch for it to be merged in.  And someone to say it all works. #350
