### ISSUE TITLE
unicorn can't start cause database.yml has wrong permission

### ISSUE THREAD

**Issue by marawu** [sameersbn/docker-redmine#461]
Hi, I updated redmine to 4.2.0 version and today I restarted my server and after it I got the error:

```
redmine_1  | 2021-04-07 23:04:55,861 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2021-04-07 23:04:55,861 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2021-04-07 23:04:56,864 INFO spawned: 'unicorn' with pid 315
redmine_1  | 2021-04-07 23:04:58,171 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2021-04-07 23:04:58,172 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2021-04-07 23:04:59,174 INFO spawned: 'unicorn' with pid 316
redmine_1  | 2021-04-07 23:05:00,428 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2021-04-07 23:05:00,428 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2021-04-07 23:05:01,431 INFO spawned: 'unicorn' with pid 317
redmine_1  | 2021-04-07 23:05:02,695 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2021-04-07 23:05:02,695 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2021-04-07 23:05:03,698 INFO spawned: 'unicorn' with pid 319
redmine_1  | 2021-04-07 23:05:05,158 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

I found message in logs:

```
/home/redmine/redmine/Gemfile:56:in `read':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: Permission denied @ rb_sysopen - /home/redmine/redmine/config/database.yml. Bundler cannot continue.
 #  from /home/redmine/redmine/Gemfile:56
 #  -------------------------------------------
 #  if File.exist?(database_file)
 >    database_config = YAML::load(ERB.new(IO.read(database_file)).result)
 #    adapters = database_config.values.map {|c| c['adapter']}.compact.uniq
 #  -------------------------------------------
	from /home/redmine/redmine/Gemfile:56:in `eval_gemfile'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/dsl.rb:50:in `instance_eval'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/dsl.rb:50:in `eval_gemfile'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/dsl.rb:12:in `evaluate'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:33:in `build'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler.rb:194:in `definition'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler.rb:142:in `setup'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:136:in `with_level'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:88:in `silence'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/redmine/redmine/Gemfile:56:in `read': Permission denied @ rb_sysopen - /home/redmine/redmine/config/database.yml (Errno::EACCES)
	from /home/redmine/redmine/Gemfile:56:in `eval_gemfile'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/dsl.rb:50:in `instance_eval'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/dsl.rb:50:in `eval_gemfile'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/dsl.rb:12:in `evaluate'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:33:in `build'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler.rb:194:in `definition'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler.rb:142:in `setup'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:136:in `with_level'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:88:in `silence'
	from /var/lib/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
	from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require'
```

When I changed `config/database.yml` permission from 640 to 644, unicorn started, but after restart container I got the same error. How to fix it? I tried to remove image, but it didn't help

**Comment by jcormier** [comment]
What database are you using?  And what env variables have you set?

I launched a 4.1.2 image with a fresh database.  Then switched to the 4.2.0 image and let it do the migration.  The image started just fine. And the permissions for database.yml are 640 which is correct:
```
 $ docker-compose exec redmine ls -la /home/redmine/redmine/config/database.yml
-rw-r----- 1 redmine redmine 170 Apr  8 03:02 /home/redmine/redmine/config/database.yml
```

> When I changed `config/database.yml` permission from 640 to 644, unicorn started, but after restart container I got the same error. How to fix it? I tried to remove image, but it didn't help
The fact that setting the other permission value worked must mean that either unicorn is not being started as the redmine user or your database.yml file isn't owned by the redmine user.  I'm not sure how either of these things could be wrong, but know how you start/configure the image may help reproduce this.

**Comment by jcormier** [comment]
FYI, I tested with the postgres database

**Comment by jcormier** [comment]
@torer Could you post the full log?  How are you launching the docker?
