### ISSUE TITLE
S3 file attachement stop workgin in version 4.2.2

### ISSUE THREAD

**Issue by flolopdel** [sameersbn/docker-redmine#500]
After version 4.2.2 the attach file to any issue seem to have an issue. I am using GCS bucket connecting from redmine_s3 plugins, which was working fine for version 4.2.1 and before

There are not too many changes from version 4.2.1 (attach file works) to 4.2.2 (attach file does not work). Just ubuntu focal base image change,

https://github.com/sameersbn/docker-redmine/compare/4.2.1...4.2.2

The error is the next

```
ArgumentError: :data must be provided as a String, Pathname, File, or an object that responds to #read and #eof?
  from aws/s3/data_options.rb:126:in `validate_data!'
  from aws/s3/data_options.rb:32:in `compute_write_options'
  from aws/s3/s3_object.rb:602:in `write'
  from plugins/redmine_s3/lib/redmine_s3/connection.rb:114:in `put'
  from plugins/redmine_s3/lib/redmine_s3/attachment_patch.rb:26:in `put_to_s3'
  from active_support/callbacks.rb:426:in `block in make_lambda'
  from active_support/callbacks.rb:247:in `block in halting'
  from active_support/callbacks.rb:517:in `block in invoke_after'
  from active_support/callbacks.rb:517:in `each'
  from active_support/callbacks.rb:517:in `invoke_after'
  from active_support/callbacks.rb:133:in `run_callbacks'
  from active_support/callbacks.rb:816:in `_run_validation_callbacks'
  from active_model/validations/callbacks.rb:118:in `run_validations!'
  from active_model/validations.rb:339:in `valid?'
  from active_record/validations.rb:67:in `valid?'
  from active_record/validations.rb:84:in `perform_validations'
  from active_record/validations.rb:46:in `save'
  from active_record/transactions.rb:310:in `block (2 levels) in save'
  from active_record/transactions.rb:387:in `block in with_transaction_returning_status'
  from active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
  from active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
  from monitor.rb:235:in `mon_synchronize'
  from active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/transactions.rb:385:in `with_transaction_returning_status'
  from active_record/transactions.rb:310:in `block in save'
  from active_record/transactions.rb:325:in `rollback_active_record_state!'
  from active_record/transactions.rb:309:in `save'
  from active_record/suppressor.rb:44:in `save'
  from app/controllers/attachments_controller.rb:112:in `upload'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:194:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from lib/redmine/sudo_mode.rb:61:in `sudo_mode'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from action_controller/metal/instrumentation.rb:34:in `block in process_action'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from action_controller/metal/instrumentation.rb:32:in `process_action'
  from action_controller/metal/params_wrapper.rb:256:in `process_action'
  from active_record/railties/controller_runtime.rb:24:in `process_action'
  from abstract_controller/base.rb:134:in `process'
  from action_view/rendering.rb:32:in `process'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:52:in `dispatch'
  from action_dispatch/routing/route_set.rb:34:in `serve'
  from action_dispatch/journey/router.rb:52:in `block in serve'
  from action_dispatch/journey/router.rb:35:in `each'
  from action_dispatch/journey/router.rb:35:in `serve'
  from action_dispatch/routing/route_set.rb:840:in `call'
  from rack/openid.rb:98:in `call'
  from request_store/middleware.rb:9:in `call'
  from rack/tempfile_reaper.rb:15:in `call'
  from rack/etag.rb:27:in `call'
  from rack/conditional_get.rb:40:in `call'
  from rack/head.rb:12:in `call'
  from action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack/session/abstract/id.rb:266:in `context'
  from rack/session/abstract/id.rb:260:in `call'
  from action_dispatch/middleware/cookies.rb:670:in `call'
  from action_dispatch/middleware/callbacks.rb:28:in `block in call'
  from active_support/callbacks.rb:98:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from rack/method_override.rb:24:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from action_dispatch/middleware/static.rb:127:in `call'
  from rack/sendfile.rb:110:in `call'
  from rack/content_length.rb:17:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from rails/engine.rb:524:in `call'
  from unicorn/http_server.rb:606:in `process_client'
  from unicorn/http_server.rb:701:in `worker_loop'
  from unicorn/http_server.rb:549:in `spawn_missing_workers'
  from unicorn/http_server.rb:142:in `start'
  from /home/redmine/data/tmp/bundle/ruby/2.6.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
  from vendor/bundle/ruby/2.6.0/bin/unicorn_rails:23:in `load'
  from vendor/bundle/ruby/2.6.0/bin/unicorn_rails:23:in `<main>'
```

**Comment by flolopdel** [comment]
The error come from an upgrade of redmine project itself which add a different way to manage the post body
![image (1)](https://user-images.githubusercontent.com/6997633/162194484-46a19da0-52fd-4418-a527-f58b6545ee4c.png)

https://github.com/redmine/redmine/compare/4.2.1...4.2.2#diff-d131f9c19cb626b37f046169761da15c3a72a11c716b821ea021e25d568be7f1
